### ISSUE TITLE
Styler writes log to root of boot volume

### ISSUE THREAD

**Issue by LewisR** [altsan/os2-estyler#5]
Styler doesn't seem to respect %LOGFILES%. Perhaps this is by design, or perhaps it's because the original code predates the more common usage of that variable.

**Comment by altsan** [comment]
Normally it doesn't create a log file at all.  It only logs critical errors.  I guess the logic was that if these kinds of errors occur then they should be saved in a highly visible place.

**Comment by LewisR** [comment]
That's fine, and I'm not suggesting the behavior change, if you feel that \ is an appropriate place.
